### PR TITLE
Fix setting proper permissions on agents config files

### PR DESCRIPTION
**Pull request by matrixik**
Looks like my changes that added option to not overwrite config files by default create some problems with permissions for config and service files.

### CODE REVIEW

**Comment by witekest** [comment]
+1

**Comment by matrixik** [comment]
It's still WIP.

**Comment by matrixik** [comment]
Ready for review.

**Review by adriancz — APPROVED** [review]

**Review by witekest — APPROVED** [review]

**Comment by matrixik** [comment]
Thx for merging.

**Pull request merged**
